package com.qalens

import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * All human-facing exports. Every string emitted here is folded through [QaLensConfig.redact]
 * so no report path can leak PII or secrets. Builders are pure and depend only on an
 * [EvidenceBundle] + the active config.
 */
object QaLensReports {

    private fun ts(millis: Long) =
        SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date(millis))

    private fun clock(millis: Long) =
        SimpleDateFormat("HH:mm:ss", Locale.US).format(Date(millis))

    // ── Jira ────────────────────────────────────────────────────────────────
    fun jira(bundle: EvidenceBundle, config: QaLensConfig): String {
        fun r(s: String?) = config.redact(s.orEmpty())
        val d = bundle.snapshot.device
        val s = bundle.snapshot.screen
        return buildString {
            appendLine("h2. Bug: ${r(s.displayName)}")
            appendLine()
            appendLine("*Release Readiness:* ${bundle.score.score}/100 (${bundle.score.band})")
            appendLine("*Likely Owner:* ${bundle.classification.category.display} (${bundle.classification.confidence})")
            appendLine()

            appendLine("h3. Environment")
            appendLine("* Build: ${r(bundle.buildSafety.banner(d))}")
            appendLine("* Device: ${r(d.manufacturer)} ${r(d.deviceModel)} / Android ${r(d.androidVersion)} (SDK ${d.sdkVersion})")
            appendLine("* App: ${r(d.appName)} ${r(d.appVersion)} (${r(d.buildVariant)})")
            if (!bundle.buildSafety.isSafe) {
                bundle.buildSafety.issues.forEach { appendLine("* (!) ${r(it)}") }
            }
            appendLine()

            appendLine("h3. Reproduction")
            bundle.repro.steps.forEach { appendLine("# ${r(it.substringAfter(". "))}") }
            appendLine()
            appendLine("*Expected:* ${r(bundle.repro.expected)}")
            appendLine("*Actual:* ${r(bundle.repro.actual)}")
            appendLine()

            appendLine("h3. Likely Cause")
            appendLine("${bundle.classification.category.display} — confidence ${bundle.classification.confidence}")
            bundle.classification.reasons.forEach { appendLine("* ${r(it)}") }
            appendLine()

            appendLine("h3. Network")
            if (!bundle.networkAvailable) {
                appendLine("* Network capture unavailable — add QaLensOkHttpInterceptor to your OkHttpClient.")
            } else {
                val notable = bundle.networkEvents.filter { it.isError || it.latencyMs >= 2000 }.takeLast(8)
                if (notable.isEmpty()) appendLine("* No failed or slow requests captured.")
                notable.forEach {
                    appendLine("* ${it.method} ${r(QaLensRedactor.redactUrl(it.url, config.redactionRules))} → ${it.statusLabel} (${it.latencyLabel})${it.error?.let { e -> " $e" } ?: ""}")
                }
            }
            appendLine()

            appendLine("h3. Accessibility (${bundle.score.criticalIssues} critical, ${bundle.snapshot.warnings.size} total)")
            if (bundle.snapshot.warnings.isEmpty()) appendLine("* None")
            bundle.snapshot.warnings.take(12).forEach {
                appendLine("* [${it.severity}] ${r(it.title)} — ${r(it.description)}")
            }
            appendLine()

            bundle.contractResult?.let { cr ->
                appendLine("h3. Screen Contract (${cr.passCount}/${cr.total})")
                cr.results.forEach {
                    appendLine("* ${if (it.passed) "(/)" else "(x)"} ${r(it.description)}${it.detail?.let { d -> " — ${r(d)}" } ?: ""}")
                }
                appendLine()
            }

            if (bundle.featureFlags.isNotEmpty()) {
                appendLine("h3. Feature Flags")
                bundle.featureFlags.forEach { (k, v) -> appendLine("* ${r(k)} = ${if (v) "ON" else "OFF"}") }
                appendLine()
            }

            if (bundle.dataSources.isNotEmpty()) {
                bundle.dataSources.forEach { (source, values) ->
                    appendLine("h3. $source")
                    values.forEach { (k, v) -> appendLine("* ${r(k)} = ${r(v)}") }
                    appendLine()
                }
            }

            appendLine("h3. Evidence")
            bundle.attachments.forEach {
                appendLine("* ${it.kind}: ${if (it.available) r(it.path) else "unavailable${it.note?.let { n -> " ($n)" } ?: ""}"}")
            }
            appendLine("* Completeness: ${bundle.completeness.percent}%" +
                if (bundle.completeness.missing.isNotEmpty()) " (missing: ${bundle.completeness.missing.joinToString("; ")})" else "")
            appendLine()
            appendLine("_Generated by QaLens · ${ts(bundle.generatedAtMillis)}_")
        }
    }

    // ── Slack ───────────────────────────────────────────────────────────────
    fun slack(bundle: EvidenceBundle, config: QaLensConfig): String {
        fun r(s: String?) = config.redact(s.orEmpty())
        val d = bundle.snapshot.device
        val s = bundle.snapshot.screen
        val emoji = when (bundle.classification.confidence) {
            Confidence.HIGH -> ":rotating_light:"
            Confidence.MEDIUM -> ":warning:"
            Confidence.LOW -> ":mag:"
        }
        return buildString {
            appendLine("$emoji *Bug · ${r(s.displayName)}*  (${r(d.environment ?: d.buildVariant)} ${r(d.appVersion)})")
            appendLine("Readiness *${bundle.score.score}/100* · Likely *${bundle.classification.category.display}* (${bundle.classification.confidence})")
            val failed = bundle.networkEvents.filter { it.isError }.takeLast(3)
            failed.forEach { appendLine("• ${it.method} ${r(it.shortUrl)} → ${it.statusLabel} (${it.latencyLabel})") }
            if (bundle.score.criticalIssues > 0) appendLine("• ${bundle.score.criticalIssues} critical a11y issue(s)")
            val path = bundle.repro.steps.take(5).joinToString(" → ") { r(it.substringAfter(". ")) }
            if (bundle.repro.hasData) appendLine("Repro: $path")
        }
    }

    // ── Repro steps only ──────────────────────────────────────────────────────
    fun repro(bundle: EvidenceBundle, config: QaLensConfig): String {
        fun r(s: String?) = config.redact(s.orEmpty())
        return buildString {
            appendLine("Reproduction Steps — ${r(bundle.snapshot.screen.displayName)}")
            appendLine()
            bundle.repro.steps.forEach { appendLine(r(it)) }
            appendLine()
            appendLine("Expected: ${r(bundle.repro.expected)}")
            appendLine("Actual:   ${r(bundle.repro.actual)}")
        }
    }

    // ── Full QA report ──────────────────────────────────────────────────────
    fun full(bundle: EvidenceBundle, config: QaLensConfig): String {
        fun r(s: String?) = config.redact(s.orEmpty())
        return buildString {
            // Reuse the detailed component-level report, then append v2 evidence sections.
            append(QaLensReportBuilder.build(bundle.snapshot, config))
            appendLine()
            appendLine("== Release Readiness ==")
            appendLine("Score: ${bundle.score.score}/100 (${bundle.score.band})")
            bundle.score.byDimension().forEach { (dim, pts) -> appendLine("- ${dim.display}: -$pts") }
            appendLine()
            appendLine("== Likely Cause ==")
            appendLine("${bundle.classification.category.display} (confidence ${bundle.classification.confidence})")
            bundle.classification.reasons.forEach { appendLine("- ${r(it)}") }
            appendLine()
            appendLine("== Timeline ==")
            if (bundle.timeline.isEmpty()) appendLine("No timeline events captured.")
            bundle.timeline.forEach { appendLine("${clock(it.timestampMillis)} [${it.kind}] ${r(it.title)}") }
            appendLine()
            appendLine("== Reproduction ==")
            bundle.repro.steps.forEach { appendLine(r(it)) }
            appendLine("Expected: ${r(bundle.repro.expected)}")
            appendLine("Actual: ${r(bundle.repro.actual)}")
            appendLine()
            bundle.contractResult?.let { cr ->
                appendLine("== Screen Contract: ${cr.passCount}/${cr.total} ==")
                cr.results.forEach {
                    appendLine("${if (it.passed) "✓" else "✕"} ${r(it.description)}${it.detail?.let { d -> " — ${r(d)}" } ?: ""}")
                }
                appendLine()
            }
            if (bundle.dataSources.isNotEmpty()) {
                bundle.dataSources.forEach { (source, values) ->
                    appendLine("== $source ==")
                    values.forEach { (k, v) -> appendLine("- ${r(k)}: ${r(v)}") }
                    appendLine()
                }
            }
            appendLine("== Evidence Completeness: ${bundle.completeness.percent}% ==")
            bundle.completeness.missing.forEach { appendLine("- missing: $it") }
        }
    }

    // ── Session summary (Screen Quality Map) ────────────────────────────────
    fun sessionSummary(
        screens: Map<String, ScreenQualitySnapshot>,
        config: QaLensConfig
    ): String {
        fun r(s: String?) = config.redact(s.orEmpty())
        val avg = ScreenQualityStore.sessionScore(screens)
        return buildString {
            appendLine("QaLens Session Summary")
            appendLine("Session score: ${avg?.let { "$it/100" } ?: "—"} · ${screens.size} screen(s) visited")
            appendLine()
            screens.values.sortedBy { it.latestScore }.forEach { s ->
                appendLine("${s.status} ${r(s.screenName).padEnd(22)} ${s.latestScore}/100  " +
                    "(visits ${s.visitCount}, crit ${s.criticalIssues}, failApi ${s.failedApis}, slowApi ${s.slowApis}, missTags ${s.missingTags})")
            }
        }
    }
}
